### PR TITLE
Update electron configuration

### PR DESCRIPTION
**Pull request by lorenzolewis**
Updated with proper configuration order, shells are not always in exact descending order

### CODE REVIEW

**Comment by Bowserinator** [comment]
Could you give an explanation of what's changed? The key order and formatting in your version differ from master so I can't diff the changes.

**Comment by lorenzolewis** [comment]
If you can recommend a good JSON batch editor, I’d be happy to upload another version that can be diffed, just had a heck of a time with this. 

I modified the electron configuration to be listed in the actual order, not numerically, since numerically is technically inaccurate. 

I also added the electron configuration semantic for a short-hand version. So 1s2 2s2 2p6 3s2 would be represented by [Ne] 3s2.

**Comment by Bowserinator** [comment]
I don't see any differences with the `"electron_configuration"` key (Did a key comparison with a short script). 

For example, erbium is still `"electron_configuration": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f12 5s2 5p6 6s2",` in your version (If I understand correctly you wanted to change it to `1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f12 5d0 6s2`)

The `"electron_configuration_semantic"` looks good though. For the formatting I would recommend writing a script to keep them in the current sorted order. I would put `electron_configuration_semantic` with the `electron_configuration` key, the current order is kind of arbitrary but it keeps the element name and common properties at the top.

**Comment by lorenzolewis** [comment]
Apologies for that, looks like when I added in the semantic line I referenced the original file and lost my changes to `"electron_configuration"`.
I tried to write a script to re-sort them and put them back into the original order, but I kept banging my head on it and can't get it to work. If you have a quick way then that might be easier otherwise I'll be stuck on that for a while aside from manually doing it.
I also saw there was a commit ahead with some spacing refinements, I ran this file through a JSON beautifier before uploading so any spacing should be even and any trailing spaces should be chopped off.

**Comment by Bowserinator** [comment]
I'll see if I can find the original script I used to sort the keys, I'll post it here sometime tomorrow

**Comment by Bowserinator** [comment]
```python
import collections
import json

desired_key_order = [
    "name",
    "appearance",
    "atomic_mass",
    "boil",
    "category",
    "color",
    "density",
    "discovered_by",
    "melt",
    "molar_heat",
    "named_by",
    "number",
    "period",
    "phase",
    "source",
    "spectral_img",
    "summary",
    "symbol",
    "xpos",
    "ypos",
    "shells",
    "electron_configuration",
    "electron_configuration_semantic",
    "electron_affinity",
    "electronegativity_pauling",
    "ionization_energies"
]

with open("table.json", "r") as f:
    table = json.loads(f.read(),
        object_pairs_hook=collections.OrderedDict)
    
    for i, element in enumerate(table["elements"]):
        table["elements"][i] = collections.OrderedDict(
            sorted(list(element.items()), key=lambda x: desired_key_order.index(x[0])))
    
    with open("table_out.json", "w") as fo:
        json.dump(table, fo, indent=4, separators=(", ", ": "))
```

I couldn't find the original script but this works. Don't forget to update the README to include the new keys (just copy paste the hydrogen data into the example in the README)

**Comment by lorenzolewis** [comment]
Awesome, just pushed another commit. I was close with my script, but not used to the error messages that Python spits out sometimes :)

**Comment by Bowserinator** [comment]
Merged.

**Pull request merged**
