### PR TITLE
Fix #4 and remove trailing spaces in category values

### LINKED ISSUE #4: Period is Incorrect
All elements have period of 1...

### PR DESCRIPTION
**Pull request by PeterBeard**
I wrote a little python script to fix the period values using the ypos values (#4) but it reordered the elements so the diff is pretty huge.

I also removed the trailing spaces from the category fields.

### CODE REVIEW

**Comment by wolfy1339** [comment]
Are you able to restore the order?
I think it would be greatly appreciated by @Bowserinator , or instore a new order that makes sense using Periodic Numbers or something like that

**Comment by PeterBeard** [comment]
The python library I used reads the JSON into a dictionary, which is unordered. I think reorganizing them by atomic number or something is a good idea though.

I'll see if I can re-order my changes to make the diff look nicer and then perhaps a second PR with atomic number ordering if nobody objects.

**Comment by wolfy1339** [comment]
I believe this will come in handy, it shows how to import JSON into an OrderedDict: http://stackoverflow.com/a/6921760/3411410

**Comment by PeterBeard** [comment]
Neat, thanks. I'll see if I can do this before I go to bed then :)

**Comment by PeterBeard** [comment]
Made a new PR with the original order preserved.

**Pull request closed without merging**
